//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::budget::Entity as Budget;
pub use super::tip::Entity as Tip;
pub use super::transactions::Entity as Transactions;
pub use super::users::Entity as Users;
