//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "expense_type")]
pub enum ExpenseType {
    #[sea_orm(string_value = "expense")]
    Expense,
    #[sea_orm(string_value = "income")]
    Income,
}
